export const porjects = [
  {
    id: "1",
    name: "Mobile Bazar",
    title: "Ecommerce Website",
    live_link: "https://precious-fudge-c1e67f.netlify.app/",
    server_link:"https://github.com/Sadekinchowdhury/old-market-server",
    client_link:"https://github.com/Sadekinchowdhury/old-market",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category:"full-stack",
    technology:"Html, Css, Tailwindcss, Javascript, Reactjs, ExpressJs, Mongodb, Firebase, JWT, Vercel",
    description: "Mobile Bazar application is a multi-vendor E-commerce website.There have 3 type of users admin,seller and buyer.Admin can handle everything like user delete,user make admin,seller verify,admin can see how much seller and buyer,Buyer can buy products,review and rivew delete,add to cart,see add to cart and payment by stripe.Every seller can add products , riview ,comment,comment delete,buy products by stripe and seee thate how much products added by him.If seller verify by admin then sellers products will be show on homepage and his profile have a right check simble. There have many feture also you can see please.",
  },
  {
    id: "2",
    name: "Fitlessian",
    title: "Fitness Tracking ",
    link: "",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category: "full-stack",
    description: "",
  },
  {
    id: "3",
    name: "E-learning",
    title: "Online Learning",
    link: "",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category:"front-end",
    description: "",
  },
  {
    id: "4",
    name: "linhaeanzol",
    title: "Fishing Blog",
    link: "https://linhaeanzol.com/",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category:"wordpress",
    description: "",
  },
  {
    id: "5",
    name: "plantesvertes",
    title: "Tree Plants",
    link: "https://www.plantesvertes.fr/",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category:"wordpress",
    description: "",
  },
  {
    id: "6",
    name: "Visa Processing",
    title: "Gutenberg blog",
    link: "https://www.plantesvertes.fr/",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category:"wordpress",
    description: "",
  },
  {
    id: "7",
    name: "Dumpster Rental",
    title: "Gutenberg blog",
    link: "https://www.plantesvertes.fr/",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category:"wordpress",
    description: "",
  },
];
