export const porjects = [
  {
    id: "1",
    name: "Mobile Bazar",
    title: "Ecommerce Website",
    live_link: "https://precious-fudge-c1e67f.netlify.app/",
    server_link:"https://github.com/Sadekinchowdhury/old-market-server",
    client_link:"https://github.com/Sadekinchowdhury/old-market",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category:"full-stack",
    technology:"Html, Css, Tailwindcss, Javascript, Reactjs, ExpressJs, Mongodb, Firebase, JWT, Vercel",
    description: "The Mobile Bazar application is a multi-vendor E-commerce website that caters to three types of users: admin, seller, and buyer. The admin possesses comprehensive control, with the ability to manage users (including deletion and promotion to admin status), verify sellers, and monitor the total number of sellers and buyers. Buyers, on the other hand, can purchase products, provide reviews, delete reviews, add items to their cart, view their cart, and make payments using Stripe.Each seller enjoys the autonomy to add products, write reviews, leave comments, delete comments, purchase products via Stripe, and track the number of products they have added. Upon verification by the admin, a seller's products become visible on the homepage, and their profile is adorned with a check symbol signifying legitimacy. Furthermore, the application boasts additional features for a seamless user experience. Users can explore and make the most of these features to enhance their interaction with the platform.",
  },
  {
    id: "2",
    name: "Fitlessian",
    title: "Fitness Tracking Application",
    live_link: "https://fitlessian.web.app/",
    server_link:"https://github.com/farukphero/fitness-tracking-web-server",
    client_link:"https://github.com/farukphero/fitness-tracking-web-client",
    img: "https://i.postimg.cc/kGzgwwnq/istockphoto-1329400066-1024x1024-transformed.jpg",
    category:"full-stack",
    technology:"Html, Css, Tailwindcss, Javascript, Reactjs, ExpressJs, Mongodb, Firebase, JWT, Vercel",
    description: "➡ Fitlessian is a full-stack fitness-tracking web app where users can track their daily activitieslike walking, running, swimming, cycling, etc.Users can add their everyday fitness goals and show the total calculated data on a chart and users also can view tutorials on any fitness-related topic.➡ Users can read health articles, make friends, chat with each other, and build a community. make it nicely writing",
  },
  {
    id: "3",
    name: "E-learning",
    title: "Online Learning platform",
    live_link: "https://e-learnig-rouge.vercel.app/",
    server_link:"",
    client_link:"https://github.com/Sadekinchowdhury/E-learnig",
    img: "https://i.postimg.cc/Znk6s9SJ/istockphoto-1369134621-1024x1024-transformed.jpg",
    category:"front-end",
    technology:"Html, Css, Tailwindcss, Javascript, Reactjs, Vercel",
    description: "Discover a world of learning convenience at our e-learning platform. Dive into a diverse range of online courses tailored to various skill levels and interests. Our platform features real-time online classes, offering interactive sessions with expert instructors for an engaging learning experience.Stay on top of your schedule with our user-friendly class timetable, ensuring you never miss a session. The sleek and intuitive dashboard provides a centralized hub for all your course materials, progress tracking, and upcoming events.Our commitment to your learning journey extends to reliable customer service. Our support team is ready to assist you whenever you need guidance or have questions. Elevate your learning experience with our e-learning platform, where education meets accessibility and simplicity.",
  },
  {
    id: "4",
    name: "Linhaeanzol",
    title: "Fishing Blog",
    link: "https://linhaeanzol.com/",
    img: "https://i.postimg.cc/yYmy5Txt/asia-1793406-640.jpg",
    category:"wordpress",
    description: "This is a blog website",
  },
  {
    id: "5",
    name: "Plantesvertes",
    title: "Tree Plants",
    link: "https://www.plantesvertes.fr/",
    img: "https://i.postimg.cc/LsRB2gY5/images-6.jpg",
    category:"wordpress",
    description: "Blog website",
  },
  {
    id: "6",
    name: "Visa Processing",
    title: "Gutenberg blog",
    link: "https://www.plantesvertes.fr/",
    img: "https://i.postimg.cc/ydnzvR9Z/istockphoto-659311392-1024x1024-1.jpg",
    category:"wordpress",
    description: "",
  },
  {
    id: "7",
    name: "Dumpster Rental",
    title: "Gutenberg blog",
    link: "https://www.plantesvertes.fr/",
    img: "https://i.postimg.cc/cCj2bBJr/images-7.jpg",
    category:"wordpress",
    description: "",
  },
];
