export const porjects = [
  {
    id: "1",
    name: "Mobile Bazar",
    title: "Ecommerce Website",
    live_link: "",
    github_link:"",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category:"full-stack",
    technology:"Html,Css,Tailwindcss,Javascript,Reactjs,ExpressJs,Mongodb,Firebase,JWT,Vercel",
    description: "",
  },
  {
    id: "2",
    name: "Fitlessian",
    title: "Fitness Tracking ",
    link: "",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category: "full-stack",
    description: "",
  },
  {
    id: "3",
    name: "E-learning",
    title: "Online Learning",
    link: "",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category:"front-end",
    description: "",
  },
  {
    id: "4",
    name: "linhaeanzol",
    title: "Fishing Blog",
    link: "https://linhaeanzol.com/",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category:"wordpress",
    description: "",
  },
  {
    id: "5",
    name: "plantesvertes",
    title: "Tree Plants",
    link: "https://www.plantesvertes.fr/",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category:"wordpress",
    description: "",
  },
  {
    id: "6",
    name: "Visa Processing",
    title: "Gutenberg blog",
    link: "https://www.plantesvertes.fr/",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category:"wordpress",
    description: "",
  },
  {
    id: "7",
    name: "Dumpster Rental",
    title: "Gutenberg blog",
    link: "https://www.plantesvertes.fr/",
    img: "https://i.postimg.cc/2826DsXm/a-MLka4qa-Ax-SEHarndz9hxj-1200-80.jpg",
    category:"wordpress",
    description: "",
  },
];
